config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers
  end
  
  root 'questions#index'



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :question
  belongs_to :answer
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@answer = Answer.new(answer_params)
		@answer.save

		redirect_to question_path(id: @answer.question_id)
	end

	private

	def answer_params
		params
			.require(:answer)
			.permit(:question_id, :body)
			.merge({ user_id: current_user.id })
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index; end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	
	def index
		@questions = Question.all
	end

	def create
		@question = Question.new(question_params)
		@question.save
		
		redirect_to @question
	end 

	def new
		@question = Question.new
	end

	def edit; end

	def show
		@question = Question.find(params[:id])
	end

	def update; end

	def destroy; end

	private

	def question_params
		params.require(:question)
			.permit(:title, :body)
			.merge({ user_id: current_user.id })
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<h3>Home</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nullref</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
	<% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong>.
		<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		<%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
	<% else %>
		<%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link' %> |
		<%= link_to 'Login', new_user_session_path, :class => 'navbar-link' %>
	<% end %>

	<p><%= link_to "Home", questions_path %></p>
</p>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<div>
<%= link_to "Ask a question", new_question_path %>
</div>

<div>
	<ul>
		<% @questions.each do |q| %>
			<li><%= link_to q.title, question_path(q.id) %></li>
		<% end %>
	</ul>
</div>

app/views/questions/new.html.erb
<h3>New</h3>

<%= form_for @question, action: 'create' do |f| %>
	<p>
		Title
		<%= f.text_field :title %>
	</p>
	<p>
		Body
		<%= f.text_area :body %>
	</p>

	<%= f.submit value: "Submit" %>
<% end %>

app/views/questions/show.html.erb
<h3><%= @question.title %></h3>

<pre><%= @question.body %></pre>

<p>Asked by: <%= @question.user.email %></p>

<% if @question.answers.any? %>
	<h3><%= @question.answers.size %> Answers</h3>

	<% @question.answers.each do |answer| %>
		<textarea readonly="readonly"><%= answer.body %></textarea>
		<p>Answered by: <%= answer.user.email %></p>
	<% end %>
<% end %>

<h3>Your Answer</h3>

<%= form_for [@question, @question.answers.build] do |f| %>
	<%= f.hidden_field :question_id, value: @question.id %>
	<%= f.text_area :body %>

	<%= f.submit %>
<% end %>